apiVersion: v1
kind: Service
metadata:
  name: mssqlservice
  labels:
    app: product-app
    service: mssqlservice
spec:
  type: NodePort
  ports:
    - port: 1433
      targetPort : 1433
  selector:
    app: product-app
    name: mssqlpod
---
apiVersion: v1
kind: Pod
metadata:
    name: mssqlpod
    labels:
        app: product-app
        name: mssqlpod
spec:
    containers:
        - name: mssqlcontainer
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Jahir.Lopez"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssqldeploy
    labels:
        name: mssqldeploy
        app: app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product-app
            name: mssqlpod
    template:
        metadata:
            name: mssqlpod
            labels:
                app: product-app
                name: mssqlpod
        spec:
            containers:
                - name: mssqlcontainer
                  image: mcr.microsoft.com/mssql/server:2022-latest
                  ports:
                    - containerPort: 1433
                  env:
                    - name: ACCEPT_EULA
                      value: "Y"
                    - name: SA_PASSWORD
                      value: "Jahir.Lopez"